build: test ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -14,4 +14,5 @@ jobs:
 
       - name: Setup SSH Keys
         run: |
-          echo "hello"
+          echo "this is an error"
+          exit 1
